const latestDocuments = [
  {
    id: 1,
    title: "Bài giảng Kỹ thuật phần mềm nâng cao",
    description: "Tóm tắt các kiến thức về OOP, Design Patterns và Agile.",
    type: "Lecture Notes",
    imageUrl: "/placeholders/doc1.jpg",
  },
  {
    id: 2,
    title: "Đề thi giữa kỳ môn Cấu trúc dữ liệu",
    description: "Các dạng bài tập về cây nhị phân, danh sách liên kết.",
    type: "Exam Paper",
    imageUrl: "/placeholders/doc2.jpg",
  },
  {
    id: 3,
    title: "Báo cáo cuối kỳ dự án Website HaUIDOC",
    description: "Báo cáo về quy trình phát triển và các tính năng chính.",
    type: "Report",
    imageUrl: "/placeholders/doc3.jpg",
  },
  {
    id: 4,
    title: "Tài liệu hướng dẫn sử dụng Moodle",
    description:
      "Hướng dẫn chi tiết cách sử dụng hệ thống Moodle cho sinh viên.",
    type: "Guide",
    imageUrl: "/placeholders/doc4.jpg",
  },
  {
    id: 5,
    title: "Luận văn tốt nghiệp: Ứng dụng AI trong y tế",
    description: "Nghiên cứu về các mô hình AI trong chẩn đoán bệnh.",
    type: "Thesis",
    imageUrl: "/placeholders/doc5.jpg",
  },
];

const recentlyViewed = [
  {
    id: 8,
    title: "Lịch sử kinh tế Việt Nam 2024",
    description: "Tổng quan các giai đoạn phát triển kinh tế VN.",
    type: "Book Chapter",
    imageUrl: "/placeholders/doc8.jpg",
  },
  {
    id: 9,
    title: "Nguyên lý Marketing cơ bản",
    description: "Các khái niệm và chiến lược Marketing cốt lõi.",
    type: "Textbook",
    imageUrl: "/placeholders/doc9.jpg",
  },
  {
    id: 10,
    title: "Nghiên cứu về blockchain và ứng dụng",
    description: "Giới thiệu công nghệ blockchain và các ứng dụng tiềm năng.",
    type: "Research Paper",
    imageUrl: "/placeholders/doc10.jpg",
  },
  {
    id: 11,
    title: "Giáo trình Java nâng cao",
    description: "Các chủ đề về JavaFX, Multithreading, JDBC.",
    type: "Course Material",
    imageUrl: "/placeholders/doc11.jpg",
  },
  {
    id: 12,
    title: "Cẩm nang phỏng vấn IT",
    description: "Bộ câu hỏi phỏng vấn phổ biến ngành IT và cách trả lời.",
    type: "Guide",
    imageUrl: "/placeholders/doc12.jpg",
  },
];

const likedDocuments = [
  {
    id: 14,
    title: "Tiếng Anh chuyên ngành CNTT",
    description: "Từ vựng và cấu trúc câu thông dụng trong CNTT.",
    type: "Study Aid",
    imageUrl: "/placeholders/doc14.jpg",
  },
  {
    id: 15,
    title: "Bài tập lớn Mạng máy tính",
    description: "Phân tích và thiết kế mạng LAN/WAN.",
    type: "Project",
    imageUrl: "/placeholders/doc15.jpg",
  },
  {
    id: 16,
    title: "Công nghệ Web hiện đại",
    description: "Giới thiệu về React, Vue, Angular và Node.js.",
    type: "Lecture Notes",
    imageUrl: "/placeholders/doc16.jpg",
  },
];

const myDocuments = [
  {
    id: 17,
    title: "Đồ án tốt nghiệp: Hệ thống quản lý thư viện",
    description: "Chi tiết về database, backend và frontend.",
    type: "Thesis",
    imageUrl: "/placeholders/doc17.jpg",
  },
  {
    id: 18,
    title: "Bài tập nhóm Kinh tế vi mô",
    description: "Phân tích thị trường và hành vi người tiêu dùng.",
    type: "Group Work",
    imageUrl: "/placeholders/doc18.jpg",
  },
  {
    id: 19,
    title: "Kế hoạch học tập cá nhân",
    description: "Mục tiêu và lộ trình học tập cho học kỳ mới.",
    type: "Personal",
    imageUrl: "/placeholders/doc19.jpg",
  },
  {
    id: 20,
    title: "Tài liệu tham khảo AI",
    description: "Các bài báo khoa học và sách về trí tuệ nhân tạo.",
    type: "Research",
    imageUrl: "/placeholders/doc20.jpg",
  },
];

const majors = [
  "An toàn thông tin",
  "Công nghệ dệt, may",
  "Công nghệ đa phương tiện",
  "Công nghệ kỹ thuật cơ điện tử",
  "Công nghệ kỹ thuật cơ điện tử ô tô",
  "Công nghệ kỹ thuật cơ khí",
  "Công nghệ kỹ thuật điện tử - viễn thông",
  "Công nghệ kỹ thuật điện tử y sinh",
  "Công nghệ kỹ thuật điện, điện tử",
  "Công nghệ kỹ thuật điều khiển và tự động hóa",
  "Công nghệ kỹ thuật hoá học",
  "Công nghệ kỹ thuật khuôn mẫu",
  "Công nghệ kỹ thuật máy tính",
  "Công nghệ kỹ thuật môi trường",
  "Công nghệ kỹ thuật nhiệt",
  "Công nghệ kỹ thuật ô tô",
  "Công nghệ thông tin",
  "Công nghệ thực phẩm",
  "Công nghệ vật liệu dệt, may",
  "Du lịch",
  "Hệ thống thông tin",
  "Hóa dược",
  "Kế toán",
  "Khoa học máy tính",
  "Kiểm toán",
  "Kinh tế đầu tư",
  "Kỹ thuật cơ khí động lực",
  "Kỹ thuật hệ thống công nghiệp",
  "Kỹ thuật phần mềm",
  "Kỹ thuật sản xuất thông minh",
  "Logistics và quản lý chuỗi cung ứng",
  "Mạng máy tính và truyền thông dữ liệu",
  "Marketing",
  "Năng lượng tái tạo",
  "Ngôn ngữ Anh",
  "Ngôn ngữ Hàn Quốc",
  "Ngôn ngữ học",
  "Ngôn ngữ Nhật",
  "Ngôn ngữ Trung Quốc",
  "Ngôn ngữ Trung Quốc (LK2+2 với ĐHKHKT Quảng Tây)",
  "Phân tích dữ liệu kinh doanh",
  "Quản trị dịch vụ du lịch và lữ hành",
  "Quản trị khách sạn",
  "Quản trị kinh doanh",
  "Quản trị nhà hàng và dịch vụ ăn uống",
  "Quản trị nhân lực",
  "Quản trị văn phòng",
  "Robot và trí tuệ nhân tạo",
  "Tài chính – Ngân hàng",
  "Thiết kế cơ khí và kiểu dáng công nghiệp",
  "Thiết kế thời trang",
  "Trung Quốc học",
];

const subjects = [
  "Triết học Mác-Lênin",
  "Giao tiếp liên văn hóa",
  "Quản lý dự án",
  "Đại số tuyến tính",
  "Giải tích",
  "Nhập môn về kỹ thuật",
  "Kinh tế chính trị Mác-Lênin",
  "Vật lý 1",
  "Xác suất thống kê",
  "Kỹ năng hoạt động công nghiệp",
  "Vật liệu và linh kiện điện tử",
  "Tiếng Anh Điện-Điện tử cơ bản 2",
  "Âm nhạc đại cương",
  "Nghệ thuật học đại cương",
  "Mỹ thuật đại cương",
  "Toán rời rạc",
  "Điện tử tương tự",
  "Lý thuyết mạch",
  "Tín hiệu và hệ thống",
  "Thực hành Điện tử cơ bản",
  "Kỹ thuật lập trình nhúng",
  "Phương pháp tính",
  "Toán kỹ thuật",
  "Chủ nghĩa xã hội khoa học",
  "Lập trình hướng đối tượng",
  "Điện tử số",
  "Thực hành điện tử tương tự",
  "Lập trình Python",
  "Kiến trúc máy tính và hệ điều hành",
  "Lịch sử Đảng Cộng sản Việt Nam",
  "Cấu trúc dữ liệu và giải thuật",
  "Xử lý tín hiệu số",
  "CAD trong điện tử",
  "Vi xử lý và cấu trúc máy tính",
  "Kiểm thử phần mềm",
  "Tư tưởng Hồ Chí Minh",
  "Đồ án cơ sở ngành",
  "Mạng máy tính và truyền thông",
  "Vi điều khiển",
  "Mạng nơ-ron nhân tạo",
  "Phát triển ứng dụng trên thiết bị di động",
  "Pháp luật đại cương",
  "Đồ án chuyên ngành",
  "Thiết kế ứng dụng trên máy tính nhúng",
  "Lập trình .NET",
  "Đo lường điều khiển bằng máy tính",
  "Thiết kế hệ thống số dùng HDL",
  "Lập trình mạng và truyền thông",
  "Học máy và nhận dạng",
  "Hệ thống nhúng cho truyền thông dữ liệu",
  "Xử lý ảnh",
  "Phát triển phần mềm dựa trên mã nguồn mở",
];

export {
  recentlyViewed,
  likedDocuments,
  myDocuments,
  latestDocuments,
  majors,
  subjects,
};
